// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AskOllama(arg1:string):Promise<string>;

export function CheckDependencies():Promise<boolean>;

export function LoadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartOllamaModel():Promise<void>;

export function Testing():Promise<void>;
