// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskOllama(arg1) {
  return window['go']['api']['App']['AskOllama'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['api']['App']['CopyToClipboard'](arg1);
}

export function LoadConfig() {
  return window['go']['api']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['api']['App']['SaveConfig'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['api']['App']['Shutdown'](arg1);
}

export function StartOllamaModel() {
  return window['go']['api']['App']['StartOllamaModel']();
}

export function Testing() {
  return window['go']['api']['App']['Testing']();
}
