// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskOllama(arg1, arg2) {
  return window['go']['api']['App']['AskOllama'](arg1, arg2);
}

export function CheckDependencies() {
  return window['go']['api']['App']['CheckDependencies']();
}

export function ClearHistory(arg1) {
  return window['go']['api']['App']['ClearHistory'](arg1);
}

export function DeleteConfig() {
  return window['go']['api']['App']['DeleteConfig']();
}

export function EnchancementQuery(arg1, arg2) {
  return window['go']['api']['App']['EnchancementQuery'](arg1, arg2);
}

export function GetUserDetails() {
  return window['go']['api']['App']['GetUserDetails']();
}

export function InstallOllamaAndPhi3() {
  return window['go']['api']['App']['InstallOllamaAndPhi3']();
}

export function LoadConfig() {
  return window['go']['api']['App']['LoadConfig']();
}

export function ModeQuery(arg1) {
  return window['go']['api']['App']['ModeQuery'](arg1);
}

export function PrePrompt(arg1) {
  return window['go']['api']['App']['PrePrompt'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['api']['App']['SaveConfig'](arg1);
}

export function SetMode(arg1) {
  return window['go']['api']['App']['SetMode'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['api']['App']['Shutdown'](arg1);
}

export function StartClipBoard() {
  return window['go']['api']['App']['StartClipBoard']();
}

export function StartOllamaModel() {
  return window['go']['api']['App']['StartOllamaModel']();
}
