// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AskOllama(arg1:string,arg2:string):Promise<string>;

export function CheckDependencies():Promise<boolean>;

export function ClearHistory(arg1:string):Promise<void>;

export function DeleteConfig():Promise<string>;

export function EnchancementQuery(arg1:string,arg2:string):Promise<void>;

export function GetUserDetails():Promise<string>;

export function InstallOllamaAndPhi3():Promise<void>;

export function LoadConfig():Promise<string>;

export function ModeQuery(arg1:string):Promise<string>;

export function PrePrompt(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartClipBoard():Promise<void>;

export function StartOllamaModel():Promise<void>;
